# Generated by Django 5.0.4 on 2024-04-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=2048)),
                ('price', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
